import soundcloud
import xml.etree.ElementTree as ET
import urllib
import subprocess
import os
import pickle

def getObjData(id='83.190.1'):    
    itemstr = 'http://api.makerfairedetroit.com/item.aspx?objectid={0}'.format(id)
    stuff = urllib.urlretrieve(itemstr)
    tree = ET.parse(stuff[0])
    root = tree.getroot()
    retVal = {}
    for child in root:
        for k,v in child.attrib.iteritems():
            retVal[k] = v
    return retVal

def textToWav(text,file_name):
   subprocess.call(["espeak", "-s120","-a150", "-w"+file_name,text])

def wavToMp3(infile='temp.wav',outfile='temp.mp3'):
    os.system('lame -s22.05k -b16k {0} {1}'.format( infile, outfile))

def generateTour(exhibitList):
    startStr = "\n\n\n You should now be at exhibit {0} located at {1}. \n\n\n"
    endStr = "\n\n\n Please pause the audio and proceed to exhibit {0} located at {1}.\n\n\n"
    exhibitData = []
    for exhibit in exhibitList:
        exhibitData.append(getObjData(id=exhibit))
    finalStr = "Welcome to your virtual tour at the Henry Ford Museum. "
    for exhibit in exhibitData:
        finalStr += endStr.format(exhibit['title'],exhibit['CurrLocation2'])     
        finalStr += startStr.format(exhibit['title'],exhibit['CurrLocation3'])   
        finalStr += exhibit['abstract']

    finalStr+="\n\n\n This concludes our tour. Thank you for visiting the Henry Ford Museum."
    return finalStr

def SendToSC(filename,title="Autogenerated"):
    pkl_file = open('sc.pkl', 'rb')
    sc = pickle.load(pkl_file)
    client = soundcloud.Client(client_id=sc['sc_id'],
                               client_secret=sc['sc_secret'],
                               username = sc['sc_un'],
                               password = sc['sc_pw'])
                           
    track = client.post('/tracks', track={
        'title': title,
        'sharing': 'public',  # make this 'public' if you want
        'asset_data': open(filename, 'rb')
        })
    print track
    print track.permalink_url
    return track.permalink_url

def buildTour(exhibitList):
    myStr = generateTour(exhibitList)
    print myStr
    textToWav(myStr,'out.wav')
    wavToMp3('out.wav','out.mp3')
    result = SendToSC('out.mp3',"HELLO WORLD!!!")

exhibitList = ['83.190.1','83.190.1','83.190.1','83.190.1']
result = buildTour(exhibitList)
print result
